package uk.gov.hmcts.darts.automation.tests;

import uk.gov.hmcts.darts.automation.utils.JsonApi;
import uk.gov.hmcts.darts.automation.utils.ApiResponse;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.apache.commons.io.FileUtils;
import org.junit.Assert;
import org.junit.jupiter.api.Assertions;
import org.openqa.selenium.*;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.FluentWait;
import org.openqa.selenium.support.ui.Wait;
import org.openqa.selenium.support.ui.WebDriverWait;
//import io.restassured.path.json.JsonPath;
import com.jayway.jsonpath.*;

import java.io.File;
import java.io.IOException;
import java.time.Duration;
import java.util.List;
import java.util.Objects;
import java.util.function.Function;

//import org.apache.logging.log4j.LogManager;
//import org.apache.logging.log4j.Logger;

import uk.gov.hmcts.darts.automation.utils.*;
import uk.gov.hmcts.darts.automation.utils.Credentials;

public class TestJsonExtract {
//	private static Logger log = LogManager.getLogger("TestJsonExtract");
//	static public Response response;
	
// Following code is for debugging purposes - data may have to be changed each time
// Tests may fail if underlying data is changed
// Commented out code is to allow tests to be run after changes have been made

@Test
	public void test1() {
		String caseNumber = "S9001021";
		String courthouse = "Harrow Crown Court";
		String hearingDate = "2024-02-21";
		String jsonString = "{\r\n"
				+ "    \"media_request_details\": [\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 13505,\r\n"
				+ "            \"case_id\": 27529,\r\n"
				+ "            \"hearing_id\": 28349,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"A3116001\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2024-01-25\",\r\n"
				+ "            \"start_ts\": \"2024-01-25T10:00:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-01-25T10:00:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 17245,\r\n"
				+ "            \"case_id\": 42192,\r\n"
				+ "            \"hearing_id\": 46290,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"A9187005\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2024-02-15\",\r\n"
				+ "            \"start_ts\": \"2024-02-15T10:00:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-02-15T10:00:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 17285,\r\n"
				+ "            \"case_id\": 42196,\r\n"
				+ "            \"hearing_id\": 46296,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"A9188005\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2024-02-15\",\r\n"
				+ "            \"start_ts\": \"2024-02-15T10:00:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-02-15T10:00:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 6614,\r\n"
				+ "            \"case_id\": 141,\r\n"
				+ "            \"hearing_id\": 223,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"CASE1009\",\r\n"
				+ "            \"courthouse_name\": \"Swansea\",\r\n"
				+ "            \"hearing_date\": \"2023-08-15\",\r\n"
				+ "            \"start_ts\": \"2023-08-15T13:07:33Z\",\r\n"
				+ "            \"end_ts\": \"2023-08-15T13:07:33Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 5553,\r\n"
				+ "            \"case_id\": 141,\r\n"
				+ "            \"hearing_id\": 142,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"CASE1009\",\r\n"
				+ "            \"courthouse_name\": \"Swansea\",\r\n"
				+ "            \"hearing_date\": \"2023-08-15\",\r\n"
				+ "            \"start_ts\": \"2023-08-15T13:07:33Z\",\r\n"
				+ "            \"end_ts\": \"2023-08-15T13:07:33Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 7753,\r\n"
				+ "            \"case_id\": 141,\r\n"
				+ "            \"hearing_id\": 11757,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"CASE1009\",\r\n"
				+ "            \"courthouse_name\": \"Swansea\",\r\n"
				+ "            \"hearing_date\": \"2023-12-05\",\r\n"
				+ "            \"start_ts\": \"2023-12-05T01:18:59Z\",\r\n"
				+ "            \"end_ts\": \"2023-12-05T09:18:59Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 7733,\r\n"
				+ "            \"case_id\": 141,\r\n"
				+ "            \"hearing_id\": 11757,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"CASE1009\",\r\n"
				+ "            \"courthouse_name\": \"Swansea\",\r\n"
				+ "            \"hearing_date\": \"2023-12-05\",\r\n"
				+ "            \"start_ts\": \"2023-12-05T01:18:59Z\",\r\n"
				+ "            \"end_ts\": \"2023-12-05T09:18:59Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 11626,\r\n"
				+ "            \"case_id\": 21,\r\n"
				+ "            \"hearing_id\": 1,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"CASE5_Event_DMP461\",\r\n"
				+ "            \"courthouse_name\": \"Swansea\",\r\n"
				+ "            \"hearing_date\": \"2023-08-10\",\r\n"
				+ "            \"start_ts\": \"2023-08-10T00:00:00Z\",\r\n"
				+ "            \"end_ts\": \"2023-08-10T00:00:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 9127,\r\n"
				+ "            \"case_id\": 21,\r\n"
				+ "            \"hearing_id\": 1,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"CASE5_Event_DMP461\",\r\n"
				+ "            \"courthouse_name\": \"Swansea\",\r\n"
				+ "            \"hearing_date\": \"2023-08-10\",\r\n"
				+ "            \"start_ts\": \"2023-08-10T00:00:00Z\",\r\n"
				+ "            \"end_ts\": \"2023-08-10T00:00:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 9128,\r\n"
				+ "            \"case_id\": 21,\r\n"
				+ "            \"hearing_id\": 1,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"CASE5_Event_DMP461\",\r\n"
				+ "            \"courthouse_name\": \"Swansea\",\r\n"
				+ "            \"hearing_date\": \"2023-08-10\",\r\n"
				+ "            \"start_ts\": \"2023-08-10T00:00:00Z\",\r\n"
				+ "            \"end_ts\": \"2023-08-10T00:00:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 5493,\r\n"
				+ "            \"case_id\": 1025,\r\n"
				+ "            \"hearing_id\": 1025,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"DMP-1025\",\r\n"
				+ "            \"courthouse_name\": \"Swansea\",\r\n"
				+ "            \"hearing_date\": \"2023-11-27\",\r\n"
				+ "            \"start_ts\": \"2023-11-15T08:37:30Z\",\r\n"
				+ "            \"end_ts\": \"2023-11-15T08:37:30Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 9126,\r\n"
				+ "            \"case_id\": 1025,\r\n"
				+ "            \"hearing_id\": 1025,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"DMP-1025\",\r\n"
				+ "            \"courthouse_name\": \"Swansea\",\r\n"
				+ "            \"hearing_date\": \"2023-11-27\",\r\n"
				+ "            \"start_ts\": \"2023-11-27T08:37:30Z\",\r\n"
				+ "            \"end_ts\": \"2023-11-27T08:37:30Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 9245,\r\n"
				+ "            \"case_id\": 1025,\r\n"
				+ "            \"hearing_id\": 1025,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"DMP-1025\",\r\n"
				+ "            \"courthouse_name\": \"Swansea\",\r\n"
				+ "            \"hearing_date\": \"2023-11-27\",\r\n"
				+ "            \"start_ts\": \"2023-11-27T08:37:30Z\",\r\n"
				+ "            \"end_ts\": \"2023-11-27T00:00:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 9265,\r\n"
				+ "            \"case_id\": 1025,\r\n"
				+ "            \"hearing_id\": 1025,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"DMP-1025\",\r\n"
				+ "            \"courthouse_name\": \"Swansea\",\r\n"
				+ "            \"hearing_date\": \"2023-11-27\",\r\n"
				+ "            \"start_ts\": \"2023-11-27T08:37:30Z\",\r\n"
				+ "            \"end_ts\": \"2023-11-27T00:00:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 9185,\r\n"
				+ "            \"case_id\": 1025,\r\n"
				+ "            \"hearing_id\": 1025,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"DMP-1025\",\r\n"
				+ "            \"courthouse_name\": \"Swansea\",\r\n"
				+ "            \"hearing_date\": \"2023-11-27\",\r\n"
				+ "            \"start_ts\": \"2023-11-27T08:37:30Z\",\r\n"
				+ "            \"end_ts\": \"2023-11-27T08:37:30Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 9246,\r\n"
				+ "            \"case_id\": 1025,\r\n"
				+ "            \"hearing_id\": 1025,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"DMP-1025\",\r\n"
				+ "            \"courthouse_name\": \"Swansea\",\r\n"
				+ "            \"hearing_date\": \"2023-11-27\",\r\n"
				+ "            \"start_ts\": \"2023-11-27T08:37:30Z\",\r\n"
				+ "            \"end_ts\": \"2023-11-27T00:00:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 9225,\r\n"
				+ "            \"case_id\": 1025,\r\n"
				+ "            \"hearing_id\": 1025,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"DMP-1025\",\r\n"
				+ "            \"courthouse_name\": \"Swansea\",\r\n"
				+ "            \"hearing_date\": \"2023-11-27\",\r\n"
				+ "            \"start_ts\": \"2023-11-27T08:37:30Z\",\r\n"
				+ "            \"end_ts\": \"2023-11-27T00:00:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 11606,\r\n"
				+ "            \"case_id\": 18589,\r\n"
				+ "            \"hearing_id\": 19409,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"DMP-1225_case1\",\r\n"
				+ "            \"courthouse_name\": \"DMP-1225_Courthouse\",\r\n"
				+ "            \"hearing_date\": \"2023-01-05\",\r\n"
				+ "            \"start_ts\": \"2023-01-05T12:01:00Z\",\r\n"
				+ "            \"end_ts\": \"2023-01-05T12:01:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 14585,\r\n"
				+ "            \"case_id\": 18589,\r\n"
				+ "            \"hearing_id\": 19409,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"DMP-1225_case1\",\r\n"
				+ "            \"courthouse_name\": \"DMP-1225_Courthouse\",\r\n"
				+ "            \"hearing_date\": \"2023-01-05\",\r\n"
				+ "            \"start_ts\": \"2023-01-05T13:00:00Z\",\r\n"
				+ "            \"end_ts\": \"2023-01-05T13:01:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 11645,\r\n"
				+ "            \"case_id\": 18589,\r\n"
				+ "            \"hearing_id\": 22569,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"DMP-1225_case1\",\r\n"
				+ "            \"courthouse_name\": \"DMP-1225_Courthouse\",\r\n"
				+ "            \"hearing_date\": \"2023-12-22\",\r\n"
				+ "            \"start_ts\": \"2023-12-22T11:46:32Z\",\r\n"
				+ "            \"end_ts\": \"2023-12-22T11:46:32Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 11185,\r\n"
				+ "            \"case_id\": 18589,\r\n"
				+ "            \"hearing_id\": 22569,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"DMP-1225_case1\",\r\n"
				+ "            \"courthouse_name\": \"DMP-1225_Courthouse\",\r\n"
				+ "            \"hearing_date\": \"2023-12-22\",\r\n"
				+ "            \"start_ts\": \"2023-12-22T11:46:32Z\",\r\n"
				+ "            \"end_ts\": \"2023-12-22T11:46:32Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 10866,\r\n"
				+ "            \"case_id\": 21750,\r\n"
				+ "            \"hearing_id\": 22289,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"DMP-1642-AC4\",\r\n"
				+ "            \"courthouse_name\": \"Swansea\",\r\n"
				+ "            \"hearing_date\": \"2023-12-22\",\r\n"
				+ "            \"start_ts\": \"2023-12-22T13:00:00Z\",\r\n"
				+ "            \"end_ts\": \"2023-12-22T13:01:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 10925,\r\n"
				+ "            \"case_id\": 21750,\r\n"
				+ "            \"hearing_id\": 22289,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"DMP-1642-AC4\",\r\n"
				+ "            \"courthouse_name\": \"Swansea\",\r\n"
				+ "            \"hearing_date\": \"2023-12-22\",\r\n"
				+ "            \"start_ts\": \"2023-12-22T13:00:00Z\",\r\n"
				+ "            \"end_ts\": \"2023-12-22T13:00:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 10945,\r\n"
				+ "            \"case_id\": 21750,\r\n"
				+ "            \"hearing_id\": 22295,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"DMP-1642-AC4\",\r\n"
				+ "            \"courthouse_name\": \"Swansea\",\r\n"
				+ "            \"hearing_date\": \"2024-01-12\",\r\n"
				+ "            \"start_ts\": \"2024-01-12T13:00:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-01-12T13:00:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 10285,\r\n"
				+ "            \"case_id\": 20869,\r\n"
				+ "            \"hearing_id\": 20849,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"DMP-2018\",\r\n"
				+ "            \"courthouse_name\": \"Swansea\",\r\n"
				+ "            \"hearing_date\": \"2024-01-11\",\r\n"
				+ "            \"start_ts\": \"2024-01-11T09:33:30Z\",\r\n"
				+ "            \"end_ts\": \"2024-01-11T09:33:30Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 10205,\r\n"
				+ "            \"case_id\": 20869,\r\n"
				+ "            \"hearing_id\": 20849,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"DMP-2018\",\r\n"
				+ "            \"courthouse_name\": \"Swansea\",\r\n"
				+ "            \"hearing_date\": \"2024-01-11\",\r\n"
				+ "            \"start_ts\": \"2024-01-11T13:00:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-01-11T13:01:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 6013,\r\n"
				+ "            \"case_id\": 8837,\r\n"
				+ "            \"hearing_id\": 8818,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"DMP795_nonapprover-case1\",\r\n"
				+ "            \"courthouse_name\": \"LEEDS_DMP795_NonApprover\",\r\n"
				+ "            \"hearing_date\": \"2023-11-21\",\r\n"
				+ "            \"start_ts\": \"2023-11-21T17:22:20Z\",\r\n"
				+ "            \"end_ts\": \"2023-11-21T17:22:20Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 16265,\r\n"
				+ "            \"case_id\": 40270,\r\n"
				+ "            \"hearing_id\": 44389,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"S1019021\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2024-02-14\",\r\n"
				+ "            \"start_ts\": \"2024-02-14T18:03:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-02-14T18:04:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 17185,\r\n"
				+ "            \"case_id\": 41689,\r\n"
				+ "            \"hearing_id\": 45730,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"S1029021\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2024-02-15\",\r\n"
				+ "            \"start_ts\": \"2024-02-15T18:03:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-02-15T18:04:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 17226,\r\n"
				+ "            \"case_id\": 42070,\r\n"
				+ "            \"hearing_id\": 46150,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"S1030021\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2024-02-15\",\r\n"
				+ "            \"start_ts\": \"2024-02-15T18:03:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-02-15T18:04:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 17265,\r\n"
				+ "            \"case_id\": 42172,\r\n"
				+ "            \"hearing_id\": 46331,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"S1031021\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2024-02-15\",\r\n"
				+ "            \"start_ts\": \"2024-02-15T18:03:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-02-15T18:04:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 19005,\r\n"
				+ "            \"case_id\": 43489,\r\n"
				+ "            \"hearing_id\": 47889,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"S1035021\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2024-02-19\",\r\n"
				+ "            \"start_ts\": \"2024-02-19T18:03:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-02-19T18:04:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 18985,\r\n"
				+ "            \"case_id\": 43489,\r\n"
				+ "            \"hearing_id\": 47889,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"S1035021\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2024-02-19\",\r\n"
				+ "            \"start_ts\": \"2024-02-19T18:03:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-02-19T18:04:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 19085,\r\n"
				+ "            \"case_id\": 43589,\r\n"
				+ "            \"hearing_id\": 47989,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"S1036021\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2024-02-19\",\r\n"
				+ "            \"start_ts\": \"2024-02-19T18:03:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-02-19T18:04:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 19066,\r\n"
				+ "            \"case_id\": 43589,\r\n"
				+ "            \"hearing_id\": 47989,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"S1036021\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2024-02-19\",\r\n"
				+ "            \"start_ts\": \"2024-02-19T18:03:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-02-19T18:04:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 18765,\r\n"
				+ "            \"case_id\": 43211,\r\n"
				+ "            \"hearing_id\": 47570,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"S1037021\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2024-02-19\",\r\n"
				+ "            \"start_ts\": \"2024-02-19T18:03:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-02-19T18:04:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 19165,\r\n"
				+ "            \"case_id\": 43211,\r\n"
				+ "            \"hearing_id\": 47570,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"S1037021\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2024-02-19\",\r\n"
				+ "            \"start_ts\": \"2024-02-19T18:03:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-02-19T18:04:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 19166,\r\n"
				+ "            \"case_id\": 43769,\r\n"
				+ "            \"hearing_id\": 48169,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"S1038021\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2024-02-19\",\r\n"
				+ "            \"start_ts\": \"2024-02-19T18:03:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-02-19T18:04:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 19245,\r\n"
				+ "            \"case_id\": 44190,\r\n"
				+ "            \"hearing_id\": 48551,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"S1047021\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2024-02-20\",\r\n"
				+ "            \"start_ts\": \"2024-02-20T18:03:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-02-20T18:04:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 19485,\r\n"
				+ "            \"case_id\": 44870,\r\n"
				+ "            \"hearing_id\": 49189,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"S1052021\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2024-02-21\",\r\n"
				+ "            \"start_ts\": \"2024-02-21T18:03:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-02-21T18:04:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 15205,\r\n"
				+ "            \"case_id\": 34149,\r\n"
				+ "            \"hearing_id\": 37749,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"S8144001\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2024-02-05\",\r\n"
				+ "            \"start_ts\": \"2024-02-05T18:03:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-02-05T18:04:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 15285,\r\n"
				+ "            \"case_id\": 36829,\r\n"
				+ "            \"hearing_id\": 40509,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"S8145001\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2024-02-05\",\r\n"
				+ "            \"start_ts\": \"2024-02-05T18:03:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-02-05T18:04:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 15265,\r\n"
				+ "            \"case_id\": 36829,\r\n"
				+ "            \"hearing_id\": 40509,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"S8145001\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2024-02-05\",\r\n"
				+ "            \"start_ts\": \"2024-02-05T18:03:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-02-05T18:04:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 15785,\r\n"
				+ "            \"case_id\": 37309,\r\n"
				+ "            \"hearing_id\": 41029,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"S8146001\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2024-02-07\",\r\n"
				+ "            \"start_ts\": \"2024-02-07T18:03:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-02-07T18:04:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 18345,\r\n"
				+ "            \"case_id\": 42949,\r\n"
				+ "            \"hearing_id\": 47109,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"S8146021\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2024-02-16\",\r\n"
				+ "            \"start_ts\": \"2024-02-16T18:03:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-02-16T18:04:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 18745,\r\n"
				+ "            \"case_id\": 43189,\r\n"
				+ "            \"hearing_id\": 47509,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"S8149021\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2024-02-16\",\r\n"
				+ "            \"start_ts\": \"2024-02-16T18:03:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-02-16T18:04:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 19665,\r\n"
				+ "            \"case_id\": 45189,\r\n"
				+ "            \"hearing_id\": 49469,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"S9001021\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2024-02-21\",\r\n"
				+ "            \"start_ts\": \"2024-02-21T18:03:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-02-21T18:04:00Z\",\r\n"
				+ "            \"media_request_status\": \"OPEN\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 15805,\r\n"
				+ "            \"case_id\": 37629,\r\n"
				+ "            \"hearing_id\": 41389,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"S990001\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2024-02-07\",\r\n"
				+ "            \"start_ts\": \"2024-02-07T18:03:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-02-07T18:04:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 9166,\r\n"
				+ "            \"case_id\": 1853,\r\n"
				+ "            \"hearing_id\": 2745,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"Swansea_case_1\",\r\n"
				+ "            \"courthouse_name\": \"Swansea\",\r\n"
				+ "            \"hearing_date\": \"2023-10-02\",\r\n"
				+ "            \"start_ts\": \"2023-10-02T10:00:00Z\",\r\n"
				+ "            \"end_ts\": \"2023-10-02T11:14:05Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 9205,\r\n"
				+ "            \"case_id\": 1853,\r\n"
				+ "            \"hearing_id\": 2745,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"Swansea_case_1\",\r\n"
				+ "            \"courthouse_name\": \"Swansea\",\r\n"
				+ "            \"hearing_date\": \"2023-10-02\",\r\n"
				+ "            \"start_ts\": \"2023-10-02T10:00:00Z\",\r\n"
				+ "            \"end_ts\": \"2023-10-02T11:14:05Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 8145,\r\n"
				+ "            \"case_id\": 10458,\r\n"
				+ "            \"hearing_id\": 12777,\r\n"
				+ "            \"request_type\": \"DOWNLOAD\",\r\n"
				+ "            \"case_number\": \"T20230001\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2023-12-07\",\r\n"
				+ "            \"start_ts\": \"2023-12-07T14:00:00Z\",\r\n"
				+ "            \"end_ts\": \"2023-12-07T14:01:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 8185,\r\n"
				+ "            \"case_id\": 10458,\r\n"
				+ "            \"hearing_id\": 12777,\r\n"
				+ "            \"request_type\": \"DOWNLOAD\",\r\n"
				+ "            \"case_number\": \"T20230001\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2023-12-07\",\r\n"
				+ "            \"start_ts\": \"2023-12-07T14:00:00Z\",\r\n"
				+ "            \"end_ts\": \"2023-12-07T14:01:00Z\",\r\n"
				+ "            \"media_request_status\": \"FAILED\"\r\n"
				+ "        }\r\n"
				+ "    ],\r\n"
				+ "    \"transformed_media_details\": [\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 17570,\r\n"
				+ "            \"transformed_media_id\": 531,\r\n"
				+ "            \"case_id\": 42452,\r\n"
				+ "            \"hearing_id\": 46591,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"S1034021\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2024-02-15\",\r\n"
				+ "            \"start_ts\": \"2024-02-15T18:03:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-02-15T18:04:00Z\",\r\n"
				+ "            \"media_request_status\": \"COMPLETED\",\r\n"
				+ "            \"transformed_media_filename\": \"S1034021_15_Feb_2024_1.mp3\",\r\n"
				+ "            \"transformed_media_format\": \"MP3\",\r\n"
				+ "            \"last_accessed_ts\": \"2024-02-19T10:41:08.355004Z\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 18908,\r\n"
				+ "            \"transformed_media_id\": 554,\r\n"
				+ "            \"case_id\": 43211,\r\n"
				+ "            \"hearing_id\": 47570,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"S1037021\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2024-02-19\",\r\n"
				+ "            \"start_ts\": \"2024-02-19T18:03:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-02-19T18:04:00Z\",\r\n"
				+ "            \"media_request_status\": \"COMPLETED\",\r\n"
				+ "            \"transformed_media_filename\": \"S1037021_19_Feb_2024_1.mp3\",\r\n"
				+ "            \"transformed_media_format\": \"MP3\",\r\n"
				+ "            \"last_accessed_ts\": \"2024-02-19T16:22:44.668832Z\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 18965,\r\n"
				+ "            \"transformed_media_id\": 555,\r\n"
				+ "            \"case_id\": 42452,\r\n"
				+ "            \"hearing_id\": 46591,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"S1034021\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2024-02-15\",\r\n"
				+ "            \"start_ts\": \"2024-02-15T18:03:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-02-15T18:04:00Z\",\r\n"
				+ "            \"media_request_status\": \"COMPLETED\",\r\n"
				+ "            \"transformed_media_filename\": \"S1034021_15_Feb_2024_1.mp3\",\r\n"
				+ "            \"transformed_media_format\": \"MP3\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 19145,\r\n"
				+ "            \"transformed_media_id\": 562,\r\n"
				+ "            \"case_id\": 43589,\r\n"
				+ "            \"hearing_id\": 47989,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"S1036021\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2024-02-19\",\r\n"
				+ "            \"start_ts\": \"2024-02-19T18:03:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-02-19T18:04:00Z\",\r\n"
				+ "            \"media_request_status\": \"COMPLETED\",\r\n"
				+ "            \"transformed_media_filename\": \"S1036021_19_Feb_2024_1.mp3\",\r\n"
				+ "            \"transformed_media_format\": \"MP3\",\r\n"
				+ "            \"last_accessed_ts\": \"2024-02-19T16:00:11.931868Z\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 19225,\r\n"
				+ "            \"transformed_media_id\": 565,\r\n"
				+ "            \"case_id\": 43769,\r\n"
				+ "            \"hearing_id\": 48169,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"S1038021\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2024-02-19\",\r\n"
				+ "            \"start_ts\": \"2024-02-19T18:03:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-02-19T18:04:00Z\",\r\n"
				+ "            \"media_request_status\": \"COMPLETED\",\r\n"
				+ "            \"transformed_media_filename\": \"S1038021_19_Feb_2024_1.mp3\",\r\n"
				+ "            \"transformed_media_format\": \"MP3\",\r\n"
				+ "            \"last_accessed_ts\": \"2024-02-20T08:22:31.635762Z\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 19625,\r\n"
				+ "            \"transformed_media_id\": 577,\r\n"
				+ "            \"case_id\": 43489,\r\n"
				+ "            \"hearing_id\": 47889,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"S1035021\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2024-02-19\",\r\n"
				+ "            \"start_ts\": \"2024-02-19T18:03:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-02-19T18:04:00Z\",\r\n"
				+ "            \"media_request_status\": \"COMPLETED\",\r\n"
				+ "            \"transformed_media_filename\": \"S1035021_19_Feb_2024_1.mp3\",\r\n"
				+ "            \"transformed_media_format\": \"MP3\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"media_request_id\": 19645,\r\n"
				+ "            \"transformed_media_id\": 578,\r\n"
				+ "            \"case_id\": 43489,\r\n"
				+ "            \"hearing_id\": 47889,\r\n"
				+ "            \"request_type\": \"PLAYBACK\",\r\n"
				+ "            \"case_number\": \"S1035021\",\r\n"
				+ "            \"courthouse_name\": \"Harrow Crown Court\",\r\n"
				+ "            \"hearing_date\": \"2024-02-19\",\r\n"
				+ "            \"start_ts\": \"2024-02-19T18:03:00Z\",\r\n"
				+ "            \"end_ts\": \"2024-02-19T18:04:00Z\",\r\n"
				+ "            \"media_request_status\": \"COMPLETED\",\r\n"
				+ "            \"transformed_media_filename\": \"S1035021_19_Feb_2024_1.mp3\",\r\n"
				+ "            \"transformed_media_format\": \"MP3\"\r\n"
				+ "        }\r\n"
				+ "    ]\r\n"
				+ "}";
        String jsonQuery = new StringBuilder("$..media_request_details[?(@.case_number=='")
        		.append(caseNumber)
        		.append("' && @.courthouse_name=='")
        		.append(courthouse)
        		.append("' && @.hearing_date=='")
        		.append(hearingDate)
        		.append("' && @.media_request_status!='COMPLETED')].media_request_status")
        		.toString();
//    	JsonPath jsonPath = JsonPath.compile(jsonQuery);
    	List<String> test = JsonPath.read(jsonString, jsonQuery);
    	System.out.println(test);
//    	log.info(requestStatus);
	}

}